// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Moon phase

#include "ui.h"

lv_obj_t * uic_Screen2;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Container_time2 = NULL;
lv_obj_t * ui_Label_time2 = NULL;
lv_obj_t * ui_Label_hrs = NULL;
lv_obj_t * ui_Label_min = NULL;
lv_obj_t * ui_Label_sec2 = NULL;
lv_obj_t * ui_Label_day = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_images_earth_png, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_images_bg_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -2);
    lv_obj_set_y(ui_Image2, 4);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_time2 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container_time2);
    lv_obj_set_width(ui_Container_time2, 403);
    lv_obj_set_height(ui_Container_time2, 128);
    lv_obj_set_x(ui_Container_time2, 1);
    lv_obj_set_y(ui_Container_time2, -92);
    lv_obj_set_align(ui_Container_time2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_time2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_time2 = lv_label_create(ui_Container_time2);
    lv_obj_set_width(ui_Label_time2, 442);
    lv_obj_set_height(ui_Label_time2, 127);
    lv_obj_set_x(ui_Label_time2, 0);
    lv_obj_set_y(ui_Label_time2, 34);
    lv_obj_set_align(ui_Label_time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_time2, "10:10:10:10");
    lv_obj_add_flag(ui_Label_time2, LV_OBJ_FLAG_HIDDEN);     /// Versteckt
    lv_obj_set_style_text_align(ui_Label_time2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_time2, &ui_font_OW80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_hrs = lv_label_create(ui_Container_time2);
    lv_obj_set_width(ui_Label_hrs, 100);
    lv_obj_set_height(ui_Label_hrs, 80);
    lv_obj_set_x(ui_Label_hrs, -45);
    lv_obj_set_y(ui_Label_hrs, 26);
    lv_obj_set_align(ui_Label_hrs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_hrs, "10");
    lv_obj_clear_flag(ui_Label_hrs, LV_OBJ_FLAG_HIDDEN);     /// Sichtbar
    lv_obj_set_style_text_align(ui_Label_hrs, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_hrs, &ui_font_OW80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_min = lv_label_create(ui_Container_time2);
    lv_obj_set_width(ui_Label_min, 100);
    lv_obj_set_height(ui_Label_min, 80);
    lv_obj_set_x(ui_Label_min, 45);
    lv_obj_set_y(ui_Label_min, 26);
    lv_obj_set_align(ui_Label_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_min, "10");
    lv_obj_clear_flag(ui_Label_min, LV_OBJ_FLAG_HIDDEN);     /// Sichtbar
    lv_obj_set_style_text_align(ui_Label_min, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_min, &ui_font_OW80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_sec2 = lv_label_create(ui_Container_time2);
    lv_obj_set_width(ui_Label_sec2, 100);
    lv_obj_set_height(ui_Label_sec2, 80);
    lv_obj_set_x(ui_Label_sec2, 135);
    lv_obj_set_y(ui_Label_sec2, 24);
    lv_obj_set_align(ui_Label_sec2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_sec2, "10");
    lv_obj_clear_flag(ui_Label_sec2, LV_OBJ_FLAG_HIDDEN);     /// Sichtbar
    lv_obj_set_style_text_align(ui_Label_sec2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_sec2, &ui_font_OW80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_day = lv_label_create(ui_Container_time2);
    lv_obj_set_width(ui_Label_day, 100);
    lv_obj_set_height(ui_Label_day, 80);
    lv_obj_set_x(ui_Label_day, -135);
    lv_obj_set_y(ui_Label_day, 26);
    lv_obj_set_align(ui_Label_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_day, "10");
    lv_obj_clear_flag(ui_Label_day, LV_OBJ_FLAG_HIDDEN);     /// Sichtbar
    lv_obj_set_style_text_align(ui_Label_day, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_day, &ui_font_OW80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_colon1 = lv_label_create(ui_Container_time2);
    lv_obj_set_width(ui_Label_colon1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_colon1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_colon1, -90);
    lv_obj_set_y(ui_Label_colon1, 26);
    lv_obj_set_align(ui_Label_colon1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_colon1, ":");
    lv_obj_set_style_text_font(ui_Label_colon1, &ui_font_OW80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_colon2 = lv_label_create(ui_Container_time2);
    lv_obj_set_width(ui_Label_colon2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_colon2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_colon2, 0);
    lv_obj_set_y(ui_Label_colon2, 26);
    lv_obj_set_align(ui_Label_colon2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_colon2, ":");
    lv_obj_set_style_text_font(ui_Label_colon2, &ui_font_OW80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_colon3 = lv_label_create(ui_Container_time2);
    lv_obj_set_width(ui_Label_colon3, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label_colon3, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label_colon3, 90);
    lv_obj_set_y(ui_Label_colon3, 26);
    lv_obj_set_align(ui_Label_colon3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_colon3, ":");
    lv_obj_set_style_text_font(ui_Label_colon3, &ui_font_OW80, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Image3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image3, &ui_img_images_earth_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 1);
    lv_obj_set_y(ui_Image3, 162);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -135);
    lv_obj_set_y(ui_Label1, -12);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "TAGE");

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 135);
    lv_obj_set_y(ui_Label3, -8);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "SEKUNDEN");
    lv_obj_set_style_pad_left(ui_Label3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 481);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, 1);
    lv_obj_set_y(ui_Container1, 20);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 45);
    lv_obj_set_y(ui_Label2, -13);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "MINUTEN");

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -45);
    lv_obj_set_y(ui_Label7, -13);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "STUNDEN");

    ui_Image6 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image6, &ui_img_images_moon_moon_8_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -100);
    lv_obj_set_y(ui_Image6, -155);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image6, 825);
    lv_img_set_zoom(ui_Image6, 100);
    lv_obj_set_style_img_recolor(ui_Image6, lv_color_hex(0xFF3300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image6, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 60);
    lv_obj_set_y(ui_Label4, -150);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "END OF");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xD8B192), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_OW50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image5, &ui_img_653650985);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 90);
    lv_obj_set_y(ui_Image5, 130);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 85);

    ui_Label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -110);
    lv_obj_set_y(ui_Label5, 37);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "DAY");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xE3E4CA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_OW50, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Screen2 = ui_Screen2;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    uic_Screen2 = NULL;
    ui_Screen2 = NULL;
    ui_Image2 = NULL;
    ui_Container_time2 = NULL;
    ui_Label_time2 = NULL;
    ui_Label_hrs = NULL;
    ui_Label_min = NULL;
    ui_Label_sec2 = NULL;
    ui_Label_day = NULL;
    ui_Image3 = NULL;
    ui_Label1 = NULL;
    ui_Label3 = NULL;
    ui_Container1 = NULL;
    ui_Label2 = NULL;
    ui_Label7 = NULL;
    ui_Image6 = NULL;
    ui_Label4 = NULL;
    ui_Image5 = NULL;
    ui_Label5 = NULL;

}
