// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Moon phase

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container_time2;
extern lv_obj_t * ui_Label_time2;
extern lv_obj_t * ui_Label_hrs;
extern lv_obj_t * ui_Label_min;
extern lv_obj_t * ui_Label_sec2;
extern lv_obj_t * ui_Label_day;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

